export const countries = [
   'Argentina',
   'Greece',
   'Czech Republic',
   'Equatorial Guinea',
   'Russia',
   'Ethiopia',
   'Ukraine',
   'United Arab Emirates',
   'Indonesia',
   'Philippines',
   'Palestinian Territory',
   'France',
   'Cuba',
   'Peru',
   'Poland',
   'Sweden',
   'Colombia',
   'United States',
   'Ivory Coast',
   'China',
   'Canada',
   'Finland',
   'Turkmenistan',
   'Brazil',
   'Iran',
   'Paraguay',
   'Denmark',
   'Netherlands',
   'Uganda',
   'Madagascar',
   'Malaysia',
   'Cameroon',
   'Serbia',
   'Morocco',
   'Thailand',
   'Portugal',
   'Japan',
   'Bolivia',
   'Oman',
   'Mauritania',
   'Nepal',
   'Panama',
   'South Korea',
   'South Africa',
   'Nigeria',
   'Ireland',
   'Democratic Republic of the Congo',
   'Luxembourg',
   'Tanzania',
   'Venezuela',
   'Yemen',
   'Chile',
   'Syria',
   'Vanuatu',
   'Burkina Faso',
   'Azerbaijan',
]
